name: "publish "

on:
  workflow_dispatch:
  push:
    branches:
      - release

jobs:
  publish-tauri-linux:
    permissions:
      contents: write
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install jq

      - name: Extract Tauri config values
        id: tauri_config
        run: |
          version=$(jq -r '.version' src-tauri/tauri.conf.json)
          product_name=$(jq -r '.productName' src-tauri/tauri.conf.json)
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "product_name=$product_name" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: docker build -t tauri_linux_builds .

      - name: Run container
        run: docker run --rm -v $(pwd):/mnt tauri_linux_builds

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: PcPocket v${{ steps.tauri_config.outputs.version }}
          draft: false
          prerelease: false
          tag_name: PcPocket-v${{ steps.tauri_config.outputs.version }}
          files: |
            *.AppImage
            *.deb
            *.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
